import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        mainColor: 'var(--mainColor)',
        errorColor: 'var(--errorColor)',
        mainColorAlpha: 'var(--mainColorAlpha)',
        textColor: 'var(--textColor)',
        backgroundColor: 'var(--backgroundColor)',
        borderColor: 'var(--borderColor)',
        placeHolderColor: 'var(--placeHolderColor)',
        listOptionHoverColor: 'var(--listOptionHoverColor)',
        textWhite: 'var(--textWhite)',
        backgroundOpacity: 'var(--backgroundOpacity)',
        openStroke: 'var(--openStroke)',
        openColor: 'var(--openColor)',
        completedStroke: 'var(--completedStroke)',
        completedColor: 'var(--completedColor)',
        inProgressStroke: 'var(--inProgressStroke)',
        inProgressColor: 'var(--inProgressColor)',
        urgentStroke: 'var(--urgentStroke)',
        primary: {
          100: 'var(--primary100)',
          200: 'var(--primary200)',
          300: 'var(--primary300)',
          400: 'var(--primary400)',
          500: 'var(--primary500)',
          600: 'var(--primary600)',
          700: 'var(--primary700)',
          800: 'var(--primary800)',
          900: 'var(--primary900)',
        },
        neutral: {
          100: 'var(--neutral100)',
          200: 'var(--neutral200)',
          300: 'var(--neutral300)',
          400: 'var(--neutral400)',
          500: 'var(--neutral500)',
          600: 'var(--neutral600)',
          700: 'var(--neutral700)',
          800: 'var(--neutral800)',
          900: 'var(--neutral900)',
        },
        surfacePrimary: 'var(--primary500)',
        surfaceSecondary: 'var(--primary100)',
        surfaceTertiary: 'var(--primary400)',
        surfaceRed: 'var(--openColor)',
        surfaceGreen: 'var(--completedColor)',
        surfaceYellow: 'var(--inProgressColor)',
        primaryButtonDefault: 'var(--primary500)',
        secondaryButton: 'var(--primary100)',
        tertiaryButton: 'var(--primary800)',
        textTitlePrimary: 'var(--neutral900)',
        textTitleSecondary: 'var(--primary100)',
        textBodyPrimary: 'var(--neutral600)',
        textBodySecondary: 'var(--primary100)',
        textNavBarPrimary: 'var(--primary100)',
        textNavBarSecondary: 'var(--primary800)',
        textButtonPrimary: 'var(--primary100)',
        textButtonSecondary: 'var(--neutral900)',
        textButtonGreen: 'var(--completedStroke)',
        textButtonYellow: 'var(--inProgressStroke)',
        strokeMain: 'var(--primary500)',
        strokePrimary: 'var(--primary100)',
        strokeSecondary: 'var(--neutral400)',
        strokeTertiary: 'var(--primary900)',
        strokeRed: 'var(--openColor)',
        strokeGreen: 'var(--completedColor)',
        strokeYellow: 'var(--inProgressColor)',
        logoPrimary: 'var(--primary100)',
      },
      borderRadius: {
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        hg: '40px',
      },
      boxShadow: {
        custom: '0 4px 8px 1px rgba(0, 0, 0, 0.1)',
      },
      fontFamily: {
        poppins: ['Poppins', 'serif'],
        roboto: ['Roboto', 'serif'],
      },
      container: {
        center: true, // Optional: centers the container
        padding: {
          DEFAULT: '16px', // This applies 16px padding horizontally by default
          sm: '16px', // Small screens and above
          md: '16px', // Medium screens and above
          lg: '16px', // Large screens and above
          xl: '16px', // Extra large screens and above
        },
      },

      spacing: {
        guestNav: 'var(--guestNav)',
        1: '8px',
        2: '16px',
        3: '24px',
        4: '32px',
        5: '40px',
        6: '48px',
        7: '56px',
        8: '64px',
        9: '72px',
        10: '80px',
        11: '88px',
        12: '96px',
        13: '104px',
        14: '112px',
        15: '120px',
        16: '128px',
        17: '136px',
        18: '144px',
        19: '152px',
        20: '160px',
        21: '168px',
        22: '176px',
        23: '184px',
        24: '192px',
        25: '200px',
      },
      height: {
        guestNav: 'var(--guestNav)',
      },
    },
  },
  plugins: [require('@xpd/tailwind-3dtransforms')],
};
export default config;

