import './globals.css';

import AdminNavbar from '@/app/_components/navigation/admin-navbar';
import Footer from '@/app/_components/navigation/footer';
import GuestNavbar from '@/app/_components/navigation/guest-navbar';
import type { Metadata } from 'next';
import NextTopLoader from 'nextjs-toploader';
import SearchBar from '../_components/navigation/searchbar';
import SocketComponent from '@/app/_components/socket-component';
import { SocketProvider } from '@/app/_contexts/socket-context';
import { Toaster } from 'react-hot-toast';
import Transition from './transition';
import { cookies } from 'next/headers';
import { parseJwt } from '@/app/_utils/auth';

export const metadata: Metadata = {
  title: 'Smart Sparks',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = parseJwt(cookies().get('token')?.value);

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/iocon.ico" sizes="any" />
      </head>
      <body
        className={`font-poppins ${!user && 'pt-[var(--guestNav)]'} ${
          user &&
          'pl-[calc(var(--adminNavSmall)+var(--paddingAdmin))] md:pl-[calc(var(--adminNav)+var(--paddingAdmin))] pt-[calc(var(--searchNav)+var(--paddingAdmin))] pb-[var(--paddingAdmin)] pr-[var(--paddingAdmin)]'
        } ${
          !user &&
          'bg-[url("/images/background.png")] bg-no-repeat bg-center bg-cover'
        } `}>
        <Toaster position="top-center" />
        <NextTopLoader />
        <SocketProvider>
          {!user && <GuestNavbar />}
          {user && (
            <>
              <AdminNavbar user={user} />
              <SearchBar />
            </>
          )}
          {children}
          {!user && <Footer />}
          <SocketComponent user={user} />
        </SocketProvider>
      </body>
    </html>
  );
}

